### ISSUE TITLE
Need actual node name instead of FQDN

### ISSUE THREAD

**Issue by dantheautomator** [jonlives/knife-flip#2]
In my environment we have multiple Chef Nodes per system, so nodeflip based on FQDN does not work for us. I have forked and commited my changes to my repo https://github.com/dantheautomator/knife-flip. In order to integrate the two methods, should it be an argument, or could it determine if node = fqdn, use fqdn, otherwise use node.

**Comment by jonlives** [comment]
Apologies for the delay in getting to this Dan - I'm hoping to have a look at this in the next couple of weeks.

**Comment by jonlives** [comment]
Dan,

To keep this simple I changed the search that flip uses to "fqdn:FOO OR name:FOO" as per

https://github.com/jonlives/knife-flip/commit/d45941987d68bf50d0b21b616ef1ff8d5606f9b1

This way, you won't need to add a command line paramater, and both cases will still work. This is included in version 0.1.6 which is now on Rubygems. Sorry it took a little longer than I initially said it would!
