### ISSUE TITLE
Doesn't work with nodes that don't have any recipes

### ISSUE THREAD

**Issue by bknowles** [jonlives/knife-flip#6]
So, testing this plugin with a node that has been newly created but has not yet completed a chef-client run, it looks like the code is looking for recipes to validate as being in the target environment and if the node does not currently have any recipes, then knife flip will bomb out:

Exception: NoMethodError: Undefined method or attribute `recipes' on `node'

**Comment by jonlives** [comment]
@bknowles I haven't been able to replicate this issue on blank nodes. What version of ruby, chef & knife is this happening with?

**Comment by bknowles** [comment]
That was probably with Ruby 1.8.7 and chef-client 11.8.something.  I've since upgraded to Ruby 2.0.0-something, so I should give that another try.

Thanks for the reminder!

**Comment by jonlives** [comment]
@bknowles thanks, let me know how it goes!

**Comment by jonlives** [comment]
@bknowles just chasing up old issues - did upgrading to Ruby 2.0 solve this?
