### ISSUE TITLE
Doesn't work with chefdk-1.2.20

### ISSUE THREAD

**Issue by pjelou** [jonlives/knife-flip#7]
Installed it with gem install. 
It seems that chef  does not see that there is such a plugin.

**Comment by jonlives** [comment]
did you install it with system ruby's gem install or the "chef gem install" command that comes with chefdk?

**Comment by pjelou** [comment]
Hi. I've used the chef gem install

**Comment by jonlives** [comment]
Hmm ok cool, I'll check this out - could you please gist the output of "chef gem list" and include it here?

**Comment by pjelou** [comment]
Hi. This is the output of the chef gem list command
```
activesupport (4.2.7.1)
addressable (2.4.0)
app_conf (0.4.2)
appbundler (0.10.0)
artifactory (2.5.1)
ast (2.3.0)
autoparse (0.3.3)
aws-sdk (2.7.2)
aws-sdk-core (2.7.2)
aws-sdk-resources (2.7.2)
aws-sdk-v1 (1.66.0)
aws-sigv4 (1.0.0)
berkshelf (5.5.0)
berkshelf-api-client (3.0.0)
bigdecimal (default: 1.2.8)
binding_of_caller (0.7.2)
buff-config (2.0.0)
buff-extensions (2.0.0)
buff-ignore (1.2.0)
buff-ruby_engine (1.0.0)
buff-shell_out (1.1.0)
builder (3.2.3)
bundler (1.12.5)
byebug (9.0.6)
celluloid (0.16.0)
celluloid-io (0.16.2)
CFPropertyList (2.3.4)
chef (12.18.31)
chef-config (12.18.31)
chef-dk (1.2.20)
chef-provisioning (2.1.0)
chef-provisioning-aws (2.1.0)
chef-provisioning-azure (0.6.0)
chef-provisioning-docker (0.10.0)
chef-provisioning-fog (0.20.0)
chef-provisioning-vagrant (0.11.0)
chef-sugar (3.4.0)
chef-vault (2.9.1)
chef-zero (5.2.0)
cheffish (4.1.0)
chefspec (5.3.0)
cleanroom (1.0.0)
coderay (1.1.1)
colorize (0.8.1)
cookbook-omnifetch (0.5.0)
cookstyle (1.2.0)
cucumber (2.4.0)
cucumber-core (1.5.0)
cucumber-wire (0.0.1)
dco (1.0.1)
debug_inspector (0.0.2)
dep-selector-libgecode (1.3.1)
dep_selector (1.0.4)
did_you_mean (1.0.0)
diff-lcs (1.3)
diffy (3.1.0)
docker-api (1.33.2, 1.32.1)
domain_name (0.5.20161129)
erubis (2.7.0)
excon (0.54.0)
extlib (0.9.16)
faraday (0.9.2)
fauxhai (3.10.0)
ffi (1.9.17)
ffi-rzmq (2.0.4)
ffi-rzmq-core (1.0.5)
ffi-yajl (2.3.0)
filesize (0.1.1)
fission (0.5.0)
fog (1.38.0)
fog-aliyun (0.1.0)
fog-atmos (0.1.0)
fog-aws (1.2.0)
fog-brightbox (0.11.0)
fog-cloudatcost (0.1.2)
fog-core (1.43.0)
fog-digitalocean (0.2.0)
fog-dynect (0.0.3)
fog-ecloud (0.3.0)
fog-google (0.1.0)
fog-json (1.0.2)
fog-local (0.3.1)
fog-openstack (0.1.19)
fog-powerdns (0.1.1)
fog-profitbricks (3.0.0)
fog-rackspace (0.1.4)
fog-radosgw (0.0.5)
fog-riakcs (0.1.0)
fog-sakuracloud (1.7.5)
fog-serverlove (0.1.2)
fog-softlayer (1.1.4)
fog-storm_on_demand (0.1.1)
fog-terremark (0.1.0)
fog-vmfusion (0.1.0)
fog-voxel (0.1.0)
fog-vsphere (1.7.0)
fog-xenserver (0.2.3)
fog-xml (0.1.2)
foodcritic (8.2.0)
formatador (0.2.5)
fuzzyurl (0.9.0)
gherkin (4.0.0)
git (1.3.0)
google-api-client (0.8.7)
googleauth (0.5.1)
gssapi (1.2.0)
guard (2.14.0)
gyoku (1.3.1)
hashie (3.4.6)
highline (1.7.8)
hitimes (1.2.4)
http (2.1.0)
http-cookie (1.0.3)
http-form_data (1.0.1)
http_parser.rb (0.6.0)
httpclient (2.8.3)
i18n (0.7.0)
inflecto (0.0.2)
inifile (3.0.0)
iniparse (1.4.2)
inspec (1.10.0)
io-console (default: 0.4.5)
ipaddress (0.8.3)
jmespath (1.3.1)
json (1.8.6, default: 1.8.3)
jwt (1.5.6)
kitchen-docker (2.6.0)
kitchen-dokken (1.1.0)
kitchen-ec2 (1.2.0)
kitchen-inspec (0.17.0)
kitchen-vagrant (1.0.0)
knife-flip (0.1.9)
knife-ohno (0.1.0)
knife-opc (0.3.2)
knife-push (1.0.2)
knife-spork (1.6.3)
knife-supermarket (0.3.0)
knife-vsphere (1.2.17)
knife-windows (1.8.0)
launchy (2.4.3)
libyajl2 (1.2.0)
listen (3.1.5)
little-plugger (1.1.4)
logging (2.1.0)
lumberjack (1.0.11)
macaddr (1.7.1)
memoist (0.15.0)
method_source (0.8.2)
mime-types (3.1)
mime-types-data (3.2016.0521)
mini_portile2 (2.1.0)
minitar (0.5.4)
minitest (5.10.1, 5.8.3)
mixlib-archive (0.3.0)
mixlib-authentication (1.4.1)
mixlib-cli (1.7.0)
mixlib-config (2.2.4)
mixlib-install (2.1.10)
mixlib-log (1.7.1)
mixlib-shellout (2.2.7)
mixlib-versioning (1.1.0)
molinillo (0.5.5)
multi_json (1.12.1)
multi_test (0.1.2)
multipart-post (2.0.0)
nenv (0.3.0)
net-scp (1.2.1)
net-sftp (2.1.2)
net-ssh (3.2.0)
net-ssh-gateway (1.2.0)
net-ssh-multi (1.2.1)
net-telnet (0.1.1)
netaddr (1.5.1)
nio4r (2.0.0)
nokogiri (1.6.8.1)
nori (2.6.0)
notiffany (0.1.1)
octokit (4.6.2)
ohai (8.23.0)
opscode-pushy-client (2.1.2)
os (0.9.6)
paint (1.0.1)
parallel (1.10.0)
parser (2.3.3.1)
plist (3.2.0)
polyglot (0.3.5)
power_assert (0.2.6)
powerpack (0.1.1)
proxifier (1.0.3)
pry (0.10.4)
pry-byebug (3.4.2)
pry-remote (0.1.8)
pry-stack_explorer (0.4.9.2)
psych (default: 2.0.17)
rack (2.0.1)
rainbow (2.2.1)
rake (12.0.0, 10.4.2)
rb-fsevent (0.9.8)
rb-inotify (0.9.7)
rb-readline (0.5.3)
rbvmomi (1.9.4)
rdoc (5.0.0, default: 4.2.1)
retriable (1.4.1)
retryable (2.0.4)
ridley (5.1.0)
rspec (3.5.0)
rspec-core (3.5.4)
rspec-expectations (3.5.0)
rspec-its (1.2.0)
rspec-mocks (3.5.0)
rspec-support (3.5.0)
rspec_junit_formatter (0.2.3)
rubocop (0.46.0)
ruby-prof (0.16.2)
ruby-progressbar (1.8.1)
ruby-shadow (2.5.0)
ruby_dep (1.5.0)
rubygems-update (2.6.10)
rubyntlm (0.6.1)
rubyzip (1.2.0)
rufus-lru (1.1.0)
safe_yaml (1.0.4)
sawyer (0.8.1)
semverse (2.0.0)
serverspec (2.38.0)
sfl (2.3)
shellany (0.0.1)
signet (0.7.3)
slop (3.6.0)
solve (3.1.0)
specinfra (2.66.6)
sslshake (1.0.13)
stuartpreston-azure-sdk-for-ruby (0.7.2)
sys-proctable (1.1.3 universal-linux)
syslog-logger (1.6.8)
systemu (2.6.5)
test-kitchen (1.15.0)
test-unit (3.1.5)
thor (0.19.1)
thread_safe (0.3.5)
timers (4.0.4)
train (0.22.1)
treetop (1.6.8)
trollop (2.1.2)
tzinfo (1.2.2)
ubuntu_ami (0.4.1)
unf (0.1.4)
unf_ext (0.0.7.2)
unicode-display_width (1.1.3)
uuid (2.3.8)
uuidtools (2.1.5)
varia_model (0.6.0)
winrm (2.1.2)
winrm-elevated (1.1.0)
winrm-fs (1.0.1)
wmi-lite (1.0.0)
xml-simple (1.1.5)
yajl-ruby (1.3.0)
yard (0.9.8)
chef-gem-list.txt
```

**Comment by jonlives** [comment]
OK, so it's showing as installed - what command exactly did you run that wasn't working and what was the error?

**Comment by pjelou** [comment]
Hi.
This is what I've run
`[root@localhost chef-repo]# knife node show tsyhadoop01 
Node Name:   tsyhadoop01 
Environment: test 
FQDN:        tsyhadoop01.resource.bank 
IP:          172.31.57.35 
Run List:    recipe[bnhp-role-baseline], recipe[bnhp-vSphere::linux-disable-postinstall], role[ssh-long-timeout], role[X11], role[vsphere_hadoop], recipe[bnhp-push-jobs], recipe[bnhp-motd], recipe[bnhp-lro] 
Roles:       ssh-long-timeout, X11, vsphere_hadoop 
Recipes:     bnhp-role-baseline, bnhp-role-baseline::default, bnhp-vSphere::linux-disable-postinstall, bnhp-hadoop::vsphere_hostsfile, bnhp-push-jobs, bnhp-push-jobs::default, bnhp-motd, bnhp-motd::default, bnhp-unix-base::yumconfig, bnhp-vmtools::default, bnhp-linux::network_manager, bnhp-remove-AltCtrlDelete::default, bnhp-linux::linux-disable-postinstall, bnhp-gems::default, chef-client::default, chef-client::service, chef-client::systemd_service, chef-client::config, logrotate::default, chef-client::delete_validation, bnhp-chef-client::default, bnhp-chef-client::linux_client, bnhp-os-hardening::default, bnhp-os-hardening::user-control, bnhp-os-hardening::bashrc, bnhp-os-hardening::ssh, bnhp-ssh-hardening::login_alerts, bnhp-ssh-hardening::ssh_config, bnhp-os-hardening::linux-package-control, bnhp-os-hardening::linux-file-control, bnhp-os-hardening::linux-fstab, bnhp-os-hardening::linux-pam, bnhp-ServerMetaConfig::default, bnhp-unix-base::systemusers, bnhp-timezone::default, timezone-ii::default, timezone-ii::linux-generic, bnhp-ntp::default, ntp::default, resolver::default, bnhp-ssh-hardening::default, bnhp-bigfix::default, bnhp-remove-files::old-nmon-remove, bnhp-mtu::default, bnhp-push-jobs::install, bnhp-push-jobs::package, push-jobs::config, push-jobs::service, bnhp-push-jobs::service-restarter 
Platform:    redhat 7.2 
Tags: 
[root@localhost chef-repo]# knife flip tsyhadoop01 dev 
FATAL: Cannot find subcommand for: 'flip tsyhadoop01 dev' 
Available subcommands: (for details, knife SUB-COMMAND --help) 

** OPSCODE PRIVATE CHEF ORGANIZATION MANAGEMENT COMMANDS ** 
knife opc org create ORG_SHORT_NAME ORG_FULL_NAME (options) 
knife opc org delete ORG_NAME 
knife opc org edit ORG 
knife opc org list 
knife opc org show ORGNAME 
knife opc org user add ORG_NAME USER_NAME 
knife opc org user remove ORG_NAME USER_NAME 
knife opc user create USERNAME FIRST_NAME [MIDDLE_NAME] LAST_NAME EMAIL PASSWORD 
knife opc user delete USERNAME [-d] 
knife opc user edit USERNAME 
knife opc user list 
knife opc user password USERNAME [PASSWORD | --enable-external-auth] 
knife opc user show USERNAME 

** BASE COMMANDS ** 
Usage: /opt/chefdk/bin/knife (options)`

And the rest of the knife help.
I'm no expert, it looks that the knife does not see that it has the plugin installed, although the gem is installed.

**Comment by jonlives** [comment]
Ah, I think I have the solution here - flip is actually installed as a subcommand of node & role and not a top level command so you actually need to run this:

```
knife node flip tsyhadoop01 dev
```

It's in the README but given the name of the tool is knife-flip it's also a very easy mistake to make :p

**Comment by pjelou** [comment]
Great, thanks so much for your help. Works perfectly.
I'm gonna go ahead and write RTFM 100 times on the whiteboard :-)

**Comment by jonlives** [comment]
No worries at all!
